// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1xpQzJg6qORCPjp2LQ6Oc_5hyuzTx9ng',
    appId: '1:839899375553:web:f5ec0e6ef6559d06963140',
    messagingSenderId: '839899375553',
    projectId: 'login-750db',
    authDomain: 'login-750db.firebaseapp.com',
    storageBucket: 'login-750db.firebasestorage.app',
    measurementId: 'G-YT3R93XJMP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp3dAkAqo5pGxGDnmyubcJY4_FAUS-nGs',
    appId: '1:839899375553:android:e0ba4c36e123be60963140',
    messagingSenderId: '839899375553',
    projectId: 'login-750db',
    storageBucket: 'login-750db.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJ-hy4Kt2oVpbQeNu9joco4mtGwX_5AYY',
    appId: '1:839899375553:ios:a32d2c2d2c3b5060963140',
    messagingSenderId: '839899375553',
    projectId: 'login-750db',
    storageBucket: 'login-750db.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupFirebaseFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBJ-hy4Kt2oVpbQeNu9joco4mtGwX_5AYY',
    appId: '1:839899375553:ios:a32d2c2d2c3b5060963140',
    messagingSenderId: '839899375553',
    projectId: 'login-750db',
    storageBucket: 'login-750db.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupFirebaseFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1xpQzJg6qORCPjp2LQ6Oc_5hyuzTx9ng',
    appId: '1:839899375553:web:224da973e96794d1963140',
    messagingSenderId: '839899375553',
    projectId: 'login-750db',
    authDomain: 'login-750db.firebaseapp.com',
    storageBucket: 'login-750db.firebasestorage.app',
    measurementId: 'G-NZPV1CXJXV',
  );
}
